export { ReactComponent as Logo } from './logo+hamburger.svg';
export { ReactComponent as Sport } from './sportDropdown_web.svg';
export { ReactComponent as User } from './Vector.svg';
export { ReactComponent as Star } from './icon_wrapper.svg';
export { ReactComponent as Spain } from './Spain.svg';
export { ReactComponent as Jersey } from './Jersey.svg';
export { ReactComponent as Age } from './age.svg';
export { ReactComponent as Foot } from './Foot.svg';
export { ReactComponent as Height } from './Height.svg';
export { ReactComponent as Football } from './Football.svg';
export { ReactComponent as Lines } from './Line 1578.svg';
export { ReactComponent as Rectangle } from './Rectangle 7341.svg';
export { ReactComponent as Chelse } from './Avt.svg';
export { ReactComponent as Altetico } from './Atletico Madrid.svg';
export { ReactComponent as Dot } from './dot.svg';
